---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Loading a data set
```{r}
BiocManager::install("UCLouvain-CBIO/scpdata")

library(scpdata)

scpdata() # List the available datasets
```

# Loading data using the ExperimentHub interface

```{r}
eh <- ExperimentHub()
query(eh, "scpdata") # displays the names of datasets

scp <- eh[["EH3899"]] # load data
scp
```

# Loading data using the scpdata functions

```{r}
# scpdata exports a function for each of the data sets.
scp <- specht2019v2() # load data by name function
```

# Data Explore

```{r}

scp[["peptides"]]
rowData(scp)[["peptides"]]
colData(scp[["peptides"]])

scp[["proteins"]]
rowData(scp)[["proteins"]]
colData(scp[["proteins"]])

plot(scp, interactive = TRUE)
table(scp$sortday)

dF <- DataFrame(mean = rowSums(assay(scp[["proteins"]])),
                sd = rowSds(assay(scp[["proteins"]])))


rowData(scp) <- List(proteins = dF) 
rowData(scp)[["proteins"]]

hist(rowData(scp)[["proteins"]]$sd)

# Plot scatter plots of correlations
mymatrix <- assay(scp[["proteins"]])
View(mymatrix)
library(ggplot2)
library(patchwork)
for (i in 1:nrow(mymatrix)) {
  for (j in 1:nrow(mymatrix)) {
    if (i != j) {
      a <- mymatrix[i,]
      b <- mymatrix[j,]
      correlation <- cor(a, b, method = 'pearson')
      if (abs(correlation) > 0.8) {
        print(rownames(mymatrix)[i])
        print(rownames(mymatrix)[j])
        df <- data.frame(a,b)
        names(df) <- c("x", "y")
        ggplot(df, 
               aes(x = x, y = y)) + 
          geom_point()+
          labs(y= rownames(mymatrix)[j], x = rownames(mymatrix)[i])
        ggsave(paste("~/scp_practice/output_fig/",
                       rownames(mymatrix)[i],
                       rownames(mymatrix)[j], ".png", sep="_"))
        }
    }
  }
}

# Correlation matrix 
mymatrix <- assay(scp[["proteins"]])

cor_matrix <-  cor(t(mymatrix))

install.packages("textshape")
library(textshape)

new_cor_matrix <- cluster_matrix(cor_matrix, dim = "both", method = "average")

dim(new_cor_matrix)
View(new_cor_matrix)

heatmap(new_cor_matrix)

library(ggplot2)

new_cor_matrix %>% 
  tidy_matrix('car', 'var') %>%
  ggplot(aes(var, car, fill = value)) +
         geom_tile() +
          scale_fill_gradient(low="yellow", high="red") +
         theme(
             axis.text.y = element_text(size = 8)   ,
             axis.text.x = element_text(
                 size = 8, 
                 hjust = 1, 
                 vjust = 1, 
                 angle = 45
             ),   
             legend.position = 'bottom',
             legend.key.height = grid::unit(.1, 'cm'),
             legend.key.width = grid::unit(.5, 'cm')               
         ) +
         labs(subtitle = "With Clustering")

```
 








